### ISSUE TITLE
Test case ServerIT.shouldReceiveClientSentData fails with IndexOutOfBoundsException if client shuts down output

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus-tcp.java#7]
To reproduce:
- check out latest nukleus-tcp.java develop (I am on commit 90198f7)
- edit test ServerIT.shouldReceiveClientSentData to add the line `socket.shutdownOutput();` immediately before the call to k3po.finish()
- build
- observe the  test failure accompanied by the following exception stack:
```
java.lang.IndexOutOfBoundsException: limit=40 is beyond maxLimit=32
	at org.reaktivity.nukleus.tcp.internal.types.Flyweight.checkLimit(Flyweight.java:45)
	at org.reaktivity.nukleus.tcp.internal.types.stream.FrameFW.wrap(FrameFW.java:23)
	at org.reaktivity.nukleus.tcp.internal.reader.Target.handleRead(Target.java:170)
	at org.reaktivity.nukleus.tcp.internal.reader.Target$$Lambda$35/1876277049.onMessage(Unknown Source)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
	at org.reaktivity.nukleus.tcp.internal.reader.Target.process(Target.java:71)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.reaktor.test.NukleusRule$1.lambda$evaluate$0(NukleusRule.java:166)
	at org.reaktivity.reaktor.test.NukleusRule$1$$Lambda$11/866191240.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
Debugging shows the reason for the exception is a window update message (0x4000 0002) was read but had zero length, even though it is written as a full window update frame in the [client.sent.data/server/target.rpt](https://github.com/reaktivity/nukleus-tcp.spec/blob/develop/src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/client.sent.data/server/target.rpt) script.

Making a similar change in test ClientIT.shouldReceiveServerSentData produces the same exception.

**Comment by cmebarrow** [comment]
Test cases are available in my issue_7 branch.

**Comment by cmebarrow** [comment]
This may be happening because the k3po script is not expecting to read the end of stream frame before getting the closed event. If the script therefore fails and k3po closes the (memory) connection just after it did write [0x40 0x00 0x00 0x02] but before it for the rest of the window update frame, then the fact of closing may flush just that message id which would cause the condition to occur. If this theory is correct then maybe k3po needs fixing so it does not flush incomplete writes?

**Comment by cmebarrow** [comment]
I have filed the k3po issue as https://github.com/k3po/k3po/issues/397. I am closing the present bug since it is not indicative of a defect in the tcp nukleus.
