### ISSUE TITLE
ClosedChannelException

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-tcp.java#71]
```
java.nio.channels.ClosedChannelException
    at java.base/sun.nio.ch.ServerSocketChannelImpl.getLocalAddress(ServerSocketChannelImpl.java:117)
    at org.reaktivity.nukleus.tcp.internal.stream.Acceptor.hasLocalAddress(Acceptor.java:309)
    at org.reaktivity.nukleus.tcp.internal.stream.Acceptor.lambda$findPollerKey$4(Acceptor.java:275)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1625)
    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:476)
    at org.reaktivity.nukleus.tcp.internal.stream.Acceptor.findPollerKey(Acceptor.java:276)
    at org.reaktivity.nukleus.tcp.internal.stream.Acceptor.findOrRegisterKey(Acceptor.java:265)
    at org.reaktivity.nukleus.tcp.internal.stream.Acceptor.doRegister(Acceptor.java:141)
    at org.reaktivity.nukleus.tcp.internal.stream.Acceptor.lambda$connectionDone$1(Acceptor.java:249)
    at org.reaktivity.reaktor.internal.router.Router.lambda$foreach$8(Router.java:196)
    at org.reaktivity.reaktor.internal.types.ListFW.forEach(ListFW.java:47)
    at org.reaktivity.reaktor.internal.router.Router.foreach(Router.java:193)
    at org.reaktivity.reaktor.internal.acceptable.Acceptable.forEach(Acceptable.java:157)
    at org.reaktivity.nukleus.tcp.internal.stream.Acceptor.connectionDone(Acceptor.java:244)
    at org.reaktivity.nukleus.tcp.internal.stream.ReadStream.processReset(ReadStream.java:213)
    at org.reaktivity.nukleus.tcp.internal.stream.ReadStream.handleThrottle(ReadStream.java:166)
    at org.reaktivity.reaktor.internal.acceptable.Target.handleRead(Target.java:167)
    at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
    at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
    at org.reaktivity.reaktor.internal.acceptable.Target.process(Target.java:71)
    at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
    at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
    at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
    at org.reaktivity.reaktor.Reaktor$Core.doWork(Reaktor.java:190)
    at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by jitsni** [comment]
I think the following might have happened:
1. No of connections reached maximum connections, so unbind happened
2. Poller is closed (due to shutdown which might have closed ServerSocketChannel)
3. No of connections dropped below maximum connections, so it is trying to bind
